### ISSUE TITLE
go1.7没有6g 6l

### ISSUE THREAD

**Issue by dongzerun** [gaxxx/ctp#3]
go1.7 没有 6g 6l ， 现在的make.sh无法编译通过，是否要修一下？

**Comment by gaxxx** [comment]
很久没碰C++了，没时间弄这个。
看了一下swig的文档，也没有更新6g 6l相关。。。

**Comment by dongzerun** [comment]
谢了，我改用 python 去调 ctp 了，已经通过，用的是 vnpy
